### ISSUE TITLE
[DMF] Use of eSeal

### ISSUE THREAD

**Issue by jeborsel** [european-commission-europass/EDCI-Data-Model#11]
**Describe the organisation you represent**
Open Recognition Alliance , issue filed as part of a collective review process during ePIC2019 https://epic.openrecognition.org/

**Specify the *nature* of your comment**
* a remark about a specific content item

**Free text comment**
The authenticity of a Europass Credential is proven through the addition of an eIDAS compliant eSeal as a proof. An eSeal is organisational and linked to a legal entity (via a qualified device). The use of this for Verifiable Credentials limits the scalability.

**Comment by anthonycamilleri** [comment]
We acknowledge that this will limit uptake at first. The mandate the European Commission has is only for [digitally signed qualificaitons](https://ec.europa.eu/education/education-in-the-eu/european-education-area/digital-education-action-plan-action-3-digitally-signed-qualifications_en) which must be interpreted in the sense this is understood by the eIDAS Regulation.
