### ISSUE TITLE
[DMF] Institutial Representative's name and signature

### ISSUE THREAD

**Issue by IldikoMazar** [european-commission-europass/EDCI-Data-Model#2]
On the "EDCI_model" sheet of the [xlsx file](https://github.com/european-commission-europass/EDCI-Data-Model/blob/master/ECDI_model.xlsx) there is a property to specify the credential owner (row 13) but not the awarding institution's representative (in rows 19-23), whose name and signature we often find on traditional diplomas and certificates. I assume that this is because name and signature properties in a **digitally signed** credential are redundant as the credential bears the awarding body's e-Seal.

![InstituteSignature-property](https://user-images.githubusercontent.com/22633736/62537504-d6136300-b850-11e9-8018-39127db78b99.jpg)

**Comment by anthonycamilleri** [comment]
Correct,  unless there is strong demand, the eSeal is supposed to obviate the need for this kind of signature.
