### ISSUE TITLE
[DMF] Will there be different consultation rounds ? 

### ISSUE THREAD

**Issue by jeborsel** [european-commission-europass/EDCI-Data-Model#8]
**Describe the organisation you represent**
Open Recognition Alliance , issue filed as part of a collective review process during ePIC2019 https://epic.openrecognition.org/

**Specify the *nature* of your comment**
* general commentary on the whole data model

**Free text comment**
Current version available for consultation is 0.2.0, will there be consultation rounds up till version 0.5.0 which also includes revocation and detailed display properties?

**Comment by anthonycamilleri** [comment]
The intention is that consultation will be open for continued iteration over the long term.
